In [29]:
import torch
import torch.nn as nn
import torch.optim as optim
# from simpletransformers.classification import ClassificationModel
# from simpletransformers.classification import MultiLabelClassificationModel
import pandas as pd
import logging
from sklearn.metrics import f1_score, accuracy_score, roc_auc_score
import ast
import numpy as np
import re

logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

from google.colab import files
uploaded = files.upload()

Saving threshold_classifier_data.csv to threshold_classifier_data.csv


In [30]:
multi_label_classification = pd.read_csv("/content/threshold_classifier_data.csv", usecols=["text", "label"])
multi_label_classification.head()

text  label
0  The districts of Guidan-Roumji in Niger and Do...      0
1  In Burkina Faso, two districts are in alert at...      2
2   Niger: Distirit of Madarounfa is in the epide...      2
3   Mali: Kadiolo district is in alert phase with...      2
4  Spatial analysis shows an epidemic area common...      0

In [ ]:
# summary_state = summary_state.drop(columns=["State", "Count"])
# summary_state = summary_state.rename(columns={"Summary":"text", "Label":"labels"})
# summary_state = summary_state.reset_index(drop=True)

In [74]:
separation_val = int(0.7 * len(multi_label_classification))
separation_test = int(0.85 * len(multi_label_classification))
train_data = multi_label_classification[:separation_val]
val_data = multi_label_classification[separation_val:separation_test]
test_data = multi_label_classification[separation_test:]
print(len(test_data))
train_data

43


text  label
0    The districts of Guidan-Roumji in Niger and Do...      0
1    In Burkina Faso, two districts are in alert at...      2
2     Niger: Distirit of Madarounfa is in the epide...      2
3     Mali: Kadiolo district is in alert phase with...      2
4    Spatial analysis shows an epidemic area common...      0
..                                                 ...    ...
192  7 The data of Nigeria that is currently in epi...      1
193   Chad: The district of Goundi reached the aler...      1
194   Burkina Faso: The district of Kombissiri reac...      2
195   Ethiopia: 5 Woredas reached the alert thresho...      0
196   Kenya: The Suna West Sub County reached the a...      1

[197 rows x 2 columns]

In [4]:
pip install git+https://github.com/huggingface/transformers

  Cloning https://github.com/huggingface/transformers to /tmp/pip-req-build-gf6fzi7q
  Running command git clone -q https://github.com/huggingface/transformers /tmp/pip-req-build-gf6fzi7q
     |████████████████████████████████| 3.0MB 6.5MB/s 
     |████████████████████████████████| 1.1MB 40.5MB/s 
     |████████████████████████████████| 890kB 32.8MB/s 
  Created wheel for transformers: filename=transformers-2.11.0-cp36-none-any.whl size=702081 sha256=bb2eff2128f7ec698a8ac2ef1ce3e27d46ed6ca9acdd152ad2756a26620190ac
  Stored in directory: /tmp/pip-ephem-wheel-cache-ouiqjd_p/wheels/70/d3/52/b3fa4f8b8ef04167ac62e5bb2accb62ae764db2a378247490e
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=7edfcffa1692341c69acd32a2b7826d375910de25dd5be96ed4cd8f3ac247625
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built transformers sacremoses


In [ ]:
#This code does language modeling as the first initial step of fine-tuning on a cusotm WHO report of meningitis
#This is so the the model can learn some of the domain specific knowledge necessary to understand some of the indivial countries' reports
!python3 "run_language_modeling.py"  \
    --output_dir=output \
    --model_type=longformer \
    --model_name_or_path="allenai/longformer-base-4096" \
    --per_device_train_batch_size=1\
    --do_train \
    --train_data_file="finetune.txt" \

usage: run_language_modeling.py [-h] [--model_name_or_path MODEL_NAME_OR_PATH]
                                [--model_type MODEL_TYPE]
                                [--config_name CONFIG_NAME]
                                [--tokenizer_name TOKENIZER_NAME]
                                [--cache_dir CACHE_DIR]
                                [--train_data_file TRAIN_DATA_FILE]
                                [--eval_data_file EVAL_DATA_FILE]
                                [--line_by_line] [--mlm]
                                [--mlm_probability MLM_PROBABILITY]
                                [--block_size BLOCK_SIZE] [--overwrite_cache]
                                --output_dir OUTPUT_DIR
                                [--overwrite_output_dir] [--do_train]
                                [--do_eval] [--do_predict]
                                [--evaluate_during_training]
                                [--per_device_train_batch_size PER_DEVICE_TRAIN_BATCH_SIZE]
      

In [5]:
device = torch.device("cuda")
from transformers import LongformerModel, LongformerTokenizer, LongformerConfig

In [75]:
tokenizer = LongformerTokenizer.from_pretrained('allenai/longformer-base-4096')
model = LongformerModel.from_pretrained('allenai/longformer-base-4096')
model.cuda()

LongformerModel(
  (embeddings): RobertaEmbeddings(
    (word_embeddings): Embedding(50265, 768, padding_idx=1)
    (position_embeddings): Embedding(4098, 768, padding_idx=1)
    (token_type_embeddings): Embedding(1, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): LongformerSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (query_global): Linear(in_features=768, out_features=768, bias=True)
            (key_global): Linear(in_features=768, out_features=768, bias=True)
            (value_global): Linear(in_features=768, out_features=768, bias=True)
          )
          (output): BertSelfOutpu

In [76]:
torch.cuda.empty_cache()
#note when encoded the start of every token is added with an <s> for classification purposes
input_ids = tokenizer.encode("Hello, my dog is cute")  # Batch size 1
print(tokenizer.decode(input_ids))
print(tokenizer.decode(input_ids[0]))

<s> Hello, my dog is cute</s>
<s>


In [77]:
tokenized = multi_label_classification["text"]\
                                    .apply(lambda x: tokenizer.encode(x, add_special_tokens_tokens=True))
max_len = 0
for i in tokenized.values:
    if len(i) > max_len:
        max_len = len(i)
print(max_len)
#padded according to max_length so we can feed the model in batches - padding works as such, add 0s after the length
#of the original sequence l such that the new length is = max_len = 2530
padded = np.array([i + [0]*(max_len-len(i)) for i in tokenized.values])


627


In [79]:
np.array(padded.shape)
#Add masking so that know BERT knows where to attend to => so it can ignore padding
#adds a 1 everwhere where the condition of padded != 0 is satisfied, in other words everywhere there isn't padding
attention_mask = np.where(padded != 0, 1, 0)
#add global attention represented with 2 - for now just add 1 at the classification <s> token
attention_mask[:, [0, -1]] = 2
print(attention_mask)
device = torch.device("cuda")

input_ids = torch.tensor(padded).to(device)
attention_mask = torch.tensor(attention_mask).to(device)

def create_save_feature_representation():
  first_time = True
  for i in range(0,len(input_ids),2):
    with torch.no_grad():
      predictions, hidden_states = model(input_ids[i:i+2], attention_mask=attention_mask[i:i+2])
      scores = predictions[:,0,:].cpu().numpy()
      if not first_time:
        curr = np.load("lang_features.npy")
        scores = np.concatenate((curr, scores))
      else:
        first_time = False
      np.save("lang_features.npy",scores)

create_save_feature_representation()

[[2 1 1 ... 0 0 2]
 [2 1 1 ... 0 0 2]
 [2 1 1 ... 0 0 2]
 ...
 [2 1 1 ... 0 0 2]
 [2 1 1 ... 0 0 2]
 [2 1 1 ... 0 0 2]]


In [80]:
features = np.load("lang_features.npy")
print(multi_label_classification.iloc[0]["label"])
#convert the labels into numpy arrays since they are stored as string representations
# multi_label_classification["label"] = multi_label_classification["label"].apply(lambda x: np.fromstring(x[1:-1], dtype=np.float32, sep=','))

0


In [81]:
train_features, val_features, test_features = features[:separation_val], features[separation_val:separation_test], features[separation_test:]
hidden_size = features.shape[1]

#convert to float datatype that can be then cast to a tensor in PyTorch
labels = np.array([label for label in np.array(multi_label_classification["label"].values)])
train_labels, val_labels, test_labels = labels[:separation_val], labels[separation_val:separation_test], labels[separation_test:]
multi_label_classification.iloc[0]["label"].shape

train_features, val_features, test_features = torch.tensor(train_features).to(device).float(), torch.tensor(val_features).to(device).float(),  torch.tensor(test_features).to(device).float()
train_labels, val_labels, test_labels = torch.tensor(train_labels).to(device).long(), torch.tensor(val_labels).to(device).long(), torch.tensor(test_labels).to(device).long()

In [99]:

epochs = 50
neural_network = nn.Sequential(
                    nn.Linear(hidden_size, 1000),
                    nn.ReLU(),
                    nn.BatchNorm1d(1000),
                    nn.Linear(1000, 800),
                    nn.ReLU(),
                    nn.BatchNorm1d(800),
                    nn.Linear(800, 800),
                    nn.ReLU(),
                    nn.BatchNorm1d(800),
                    nn.Linear(800, 600),
                    nn.ReLU(),
                    nn.BatchNorm1d(600),
                    nn.Linear(600, 400),
                    nn.ReLU(),
                    nn.BatchNorm1d(400),
                    nn.Linear(400, 400),
                    nn.ReLU(),
                    nn.BatchNorm1d(400),
                    nn.Linear(400, 200),
                    nn.ReLU(),
                    nn.BatchNorm1d(200),
                    nn.Linear(200, 3),
                    nn.Softmax(),
                    )
neural_network.cuda()
dtype = torch.cuda.FloatTensor
neural_network.type = dtype

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(neural_network.parameters(), lr=0.47e-4)

print(train_features.dtype)

for epoch in range(epochs):
  optimizer.zero_grad()
  output = neural_network(train_features)
  loss = criterion(output, train_labels)
  print("Epoch {0} with training loss: {1} val accuracy: {2}".format(epoch, loss, test_model(val_features, val_labels)))
  loss.backward()
  optimizer.step()    

torch.float32
Epoch 0 with training loss: 1.1328552961349487 val accuracy: 0.4523809523809524
Epoch 1 with training loss: 0.9776414632797241 val accuracy: 0.4523809523809524
Epoch 2 with training loss: 0.8672659397125244 val accuracy: 0.47619047619047616
Epoch 3 with training loss: 0.7900079488754272 val accuracy: 0.42857142857142855
Epoch 4 with training loss: 0.7341287136077881 val accuracy: 0.42857142857142855
Epoch 5 with training loss: 0.6941674947738647 val accuracy: 0.42857142857142855
Epoch 6 with training loss: 0.6660510897636414 val accuracy: 0.42857142857142855
Epoch 7 with training loss: 0.6462557911872864 val accuracy: 0.42857142857142855
Epoch 8 with training loss: 0.6318109631538391 val accuracy: 0.40476190476190477
Epoch 9 with training loss: 0.6210203766822815 val accuracy: 0.40476190476190477
Epoch 10 with training loss: 0.6126052737236023 val accuracy: 0.42857142857142855
Epoch 11 with training loss: 0.6059209108352661 val accuracy: 0.42857142857142855
Epoch 12 with 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py:100: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


Epoch 16 with training loss: 0.5864028334617615 val accuracy: 0.42857142857142855
Epoch 17 with training loss: 0.5840505361557007 val accuracy: 0.42857142857142855
Epoch 18 with training loss: 0.5820032954216003 val accuracy: 0.42857142857142855
Epoch 19 with training loss: 0.5801969766616821 val accuracy: 0.42857142857142855
Epoch 20 with training loss: 0.5786017775535583 val accuracy: 0.42857142857142855
Epoch 21 with training loss: 0.5771791934967041 val accuracy: 0.42857142857142855
Epoch 22 with training loss: 0.575903058052063 val accuracy: 0.42857142857142855
Epoch 23 with training loss: 0.5747575759887695 val accuracy: 0.42857142857142855
Epoch 24 with training loss: 0.5737289786338806 val accuracy: 0.42857142857142855
Epoch 25 with training loss: 0.5728033781051636 val accuracy: 0.42857142857142855
Epoch 26 with training loss: 0.5719597339630127 val accuracy: 0.42857142857142855
Epoch 27 with training loss: 0.5711883902549744 val accuracy: 0.42857142857142855
Epoch 28 with tra

In [93]:
def convert_to_thresholds(data):
  return data>0.5

def test_model(features, labels):
  preds = neural_network(features).cpu().data.numpy()
  correct = labels.cpu().numpy()
  preds = np.argmax(preds, axis=1).astype(np.float32)
  return np.sum(correct==preds)/len(labels)

  # preds = convert_to_thresholds(preds)
  # print("F1 Score: ", f1_score(preds, correct, average="micro"))
  # print("ROC-AUC: ", roc_auc_score(correct, preds))

print(test_model(test_features, test_labels))

0.46511627906976744


/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py:100: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


##Tests on simplified 2 state binary classification problem
**Initial results tested with 20 labels:**
F1 Score: 0.53
ROC-AUC: 0.51

**Tested on only the most present 8 labels** - as done with the forecasting pipeline (to check if this is a signal to noise ratio)
F1 Score: 0.558
ROC-AUC: 0.501

So the issue here isn't due to noise - the Longformer is just not able to learn a meaningful enough feature representation that can map to the labels.

Let's try to finetune our Longformer model first on some domain-specific text - reports from the WHO that outline how they plan to defeat Meningitis by 2030. After finetuning on this data, let's try to regenerate our feature representations of our report text and see if that changes our results with the multilabel classifier

**After training a pre-trained model to do language modeling**
F1 Score: 0.5329
ROC-AUC: 0.566

The results did improve but not significantly

In [ ]:
#As input to finetune model - need to tokenize and feed in sentences into longformer
#In order to feed text into the longformer - need to pass in 3 things:
#1. input_ids which are the tokenized sentences (with the correct tags e.g. <s>)
#2. input_masks telling model where to pay attention to - i.e. where to ignore padding etc.
#3. token type ids which tell models about relationship of different sentences (e.g. relevant to question and answering datasets) 
# since our input consists of single sentences, we don't need it however

def tokenize_sentences(sentences):
  input_ids, attention_masks = [], []
  for sentence in sentences:
    #encodings is a dictionary with the encoded sequence and additional information like the attention mask
    encoded_dict = tokenizer.encode_plus(sentence, add_special_tokens=True, max_length=4096, pad_to_max_length=True, return_attention_mask=True)
    input_ids.append(encoded_dict["input_ids"])
    attention_masks.append(encoded_dict["attention_mask"])
  return input_ids, attention_masks

with open("finetune.txt", "r") as f:
  corpus = f.read().strip()
  corpus = corpus.replace('."', '".')
  #split the corpus into an array of sentences - each sentence will be its own item in the array
  sentences = re.split("(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s", corpus)
  sep = int(0.8*len(sentences))
  #save the last 20% of the data for test
  train_dataset, test_dataset = sentences[:sep], sentences[sep:]

input_ids, attention_masks = tokenize_sentences(train_dataset)
print(len(input_ids)*4096)

train_dataset, test_dataset = map(tokenize_sentences, train_sentences), map(tokenize_sentences, test_sentences)
print(train_dataset)

# config = LongformerConfig(dropout=0.2, attention_dropout=0.2)
# config.output_hidden_states = False
#note we're gonna be using the Longformer model we defined above so we don't need to define a new model here

torch.cuda.empty_cache()